#!/bin/bash
# Railway Cleanup Script
# Generated by railway_cleanup.py
# 22 projects marked for deletion

set -e

echo 'Railway Project Cleanup'
echo '========================'

# WARNING: This will delete the following projects:
#   - secure-grace
#   - wonderful-celebration
#   - fabulous-connection
#   - noble-gentleness
#   - sincere-recreation
#   - gregarious-wonder
#   - merry-warmth
#   - fulfilling-spirit
#   - discerning-expression
#   - steadfast-delight
#   - intuitive-endurance
#   - impartial-vision
#   - loyal-tranquility
#   - innovative-cooperation
#   - gentle-reprieve
#   - alert-enjoyment
#   - thriving-blessing
#   - terrific-truth
#   - NA-6
#   - NA-6
#   - NA-4
#   - NA-3

read -p 'Are you sure you want to delete these projects? (yes/no): ' confirm
if [ "$confirm" != "yes" ]; then
    echo 'Aborted.'
    exit 1
fi

echo 'Deleting: secure-grace'
# railway delete --project "secure-grace" --yes  # Not supported by CLI
# Use Railway Dashboard: https://railway.app/project/XXX/settings

echo 'Deleting: wonderful-celebration'
# railway delete --project "wonderful-celebration" --yes  # Not supported by CLI
# Use Railway Dashboard: https://railway.app/project/XXX/settings

echo 'Deleting: fabulous-connection'
# railway delete --project "fabulous-connection" --yes  # Not supported by CLI
# Use Railway Dashboard: https://railway.app/project/XXX/settings

echo 'Deleting: noble-gentleness'
# railway delete --project "noble-gentleness" --yes  # Not supported by CLI
# Use Railway Dashboard: https://railway.app/project/XXX/settings

echo 'Deleting: sincere-recreation'
# railway delete --project "sincere-recreation" --yes  # Not supported by CLI
# Use Railway Dashboard: https://railway.app/project/XXX/settings

echo 'Deleting: gregarious-wonder'
# railway delete --project "gregarious-wonder" --yes  # Not supported by CLI
# Use Railway Dashboard: https://railway.app/project/XXX/settings

echo 'Deleting: merry-warmth'
# railway delete --project "merry-warmth" --yes  # Not supported by CLI
# Use Railway Dashboard: https://railway.app/project/XXX/settings

echo 'Deleting: fulfilling-spirit'
# railway delete --project "fulfilling-spirit" --yes  # Not supported by CLI
# Use Railway Dashboard: https://railway.app/project/XXX/settings

echo 'Deleting: discerning-expression'
# railway delete --project "discerning-expression" --yes  # Not supported by CLI
# Use Railway Dashboard: https://railway.app/project/XXX/settings

echo 'Deleting: steadfast-delight'
# railway delete --project "steadfast-delight" --yes  # Not supported by CLI
# Use Railway Dashboard: https://railway.app/project/XXX/settings

echo 'Deleting: intuitive-endurance'
# railway delete --project "intuitive-endurance" --yes  # Not supported by CLI
# Use Railway Dashboard: https://railway.app/project/XXX/settings

echo 'Deleting: impartial-vision'
# railway delete --project "impartial-vision" --yes  # Not supported by CLI
# Use Railway Dashboard: https://railway.app/project/XXX/settings

echo 'Deleting: loyal-tranquility'
# railway delete --project "loyal-tranquility" --yes  # Not supported by CLI
# Use Railway Dashboard: https://railway.app/project/XXX/settings

echo 'Deleting: innovative-cooperation'
# railway delete --project "innovative-cooperation" --yes  # Not supported by CLI
# Use Railway Dashboard: https://railway.app/project/XXX/settings

echo 'Deleting: gentle-reprieve'
# railway delete --project "gentle-reprieve" --yes  # Not supported by CLI
# Use Railway Dashboard: https://railway.app/project/XXX/settings

echo 'Deleting: alert-enjoyment'
# railway delete --project "alert-enjoyment" --yes  # Not supported by CLI
# Use Railway Dashboard: https://railway.app/project/XXX/settings

echo 'Deleting: thriving-blessing'
# railway delete --project "thriving-blessing" --yes  # Not supported by CLI
# Use Railway Dashboard: https://railway.app/project/XXX/settings

echo 'Deleting: terrific-truth'
# railway delete --project "terrific-truth" --yes  # Not supported by CLI
# Use Railway Dashboard: https://railway.app/project/XXX/settings

echo 'Deleting: NA-6'
# railway delete --project "NA-6" --yes  # Not supported by CLI
# Use Railway Dashboard: https://railway.app/project/XXX/settings

echo 'Deleting: NA-6'
# railway delete --project "NA-6" --yes  # Not supported by CLI
# Use Railway Dashboard: https://railway.app/project/XXX/settings

echo 'Deleting: NA-4'
# railway delete --project "NA-4" --yes  # Not supported by CLI
# Use Railway Dashboard: https://railway.app/project/XXX/settings

echo 'Deleting: NA-3'
# railway delete --project "NA-3" --yes  # Not supported by CLI
# Use Railway Dashboard: https://railway.app/project/XXX/settings

echo ''
echo 'NOTE: Railway CLI does not support project deletion.'
echo 'Please delete manually via Railway Dashboard.'
echo ''
echo 'Projects to delete:'
echo '  - secure-grace'
echo '  - wonderful-celebration'
echo '  - fabulous-connection'
echo '  - noble-gentleness'
echo '  - sincere-recreation'
echo '  - gregarious-wonder'
echo '  - merry-warmth'
echo '  - fulfilling-spirit'
echo '  - discerning-expression'
echo '  - steadfast-delight'
echo '  - intuitive-endurance'
echo '  - impartial-vision'
echo '  - loyal-tranquility'
echo '  - innovative-cooperation'
echo '  - gentle-reprieve'
echo '  - alert-enjoyment'
echo '  - thriving-blessing'
echo '  - terrific-truth'
echo '  - NA-6'
echo '  - NA-6'
echo '  - NA-4'
echo '  - NA-3'

echo ''
echo 'Go to: https://railway.app/dashboard'