# Reusable Cloudflare Pages Workflow
# BlackRoad OS CI/CD
#
# Use this as a template for static sites deployed to Cloudflare Pages
#
# @blackroad_name: Cloudflare Pages CI
# @operator: alexa.operator.v1

name: Cloudflare Pages CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: "20"
  PNPM_VERSION: "8"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build site
        run: pnpm build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pages-build
          path: |
            out
            dist
            build
          retention-days: 7

  preview:
    name: Deploy Preview
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
      deployments: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: pages-build
          path: output

      - name: Deploy to Cloudflare Pages (Preview)
        id: deploy
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ github.event.repository.name }}
          directory: output
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}

      - name: Comment PR with preview URL
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## Cloudflare Pages Preview\n\n:globe_with_meridians: Preview: ${{ steps.deploy.outputs.url }}\n\n:link: Deployment ID: \`${{ steps.deploy.outputs.id }}\``
            })

  production:
    name: Deploy Production
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      contents: read
      deployments: write
    environment:
      name: production
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: pages-build
          path: output

      - name: Deploy to Cloudflare Pages (Production)
        id: deploy
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ github.event.repository.name }}
          directory: output
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main

      - name: Notify Slack
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "channel": "#deploys",
              "text": ":globe_with_meridians: Cloudflare Pages deployed: ${{ github.repository }}\nURL: ${{ steps.deploy.outputs.url }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  broken-links:
    name: Check Broken Links
    runs-on: ubuntu-latest
    needs: [production]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4

      - name: Wait for deployment propagation
        run: sleep 30

      - name: Check for broken links
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress --accept 200,204,301,302,307,308 './**/*.html' './**/*.md'
          fail: true

  lighthouse:
    name: Lighthouse Audit
    runs-on: ubuntu-latest
    needs: [production]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4

      - name: Wait for deployment propagation
        run: sleep 30

      - name: Run Lighthouse
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            ${{ github.event.repository.homepage }}
          uploadArtifacts: true
          temporaryPublicStorage: true

  algolia-index:
    name: Update Algolia Index
    runs-on: ubuntu-latest
    needs: [production]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push' && contains(github.event.repository.name, 'docs')
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run DocSearch scraper
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
        run: |
          npx @algolia/cli crawl \
            --config docsearch.config.json
